name: Basic Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print message
        run: echo "GitHub Actions is working correctly"

      - name: Check secret exists
        env:
          TRAINING_SECRET: ${{ secrets.TRAINING_SECRET }}
        run: |
          if [ -z "$TRAINING_SECRET" ]; then
            echo "Secret is missing"
            exit 1
          else
            echo "Secret exists"
          fi